- id: blackdoc
  name: blackdoc
  entry: blackdoc
  language: python
  language_version: python3
  require_serial: true
  types: [file]
  types_or: [python, rst, markdown]

- id: blackdoc-autoupdate-black
  name: autoupdate-black
  entry: python -m blackdoc.autoupdate
  language: python
  language_version: python3
  require_serial: true
  types: [file]
  files: ^\.pre-commit-config\.yaml$
