- id: blackdoc
  name: blackdoc
  entry: blackdoc
  language: python
  language_version: python3
  require_serial: true
  types:
  - file
  files: \.(py|rst)$
  additional_dependencies:
  - black~=22.1.0
