version: 2

build:
  os: ubuntu-22.04
  tools:
    python: "3.12"
  jobs:
    post_checkout:
      - (git --no-pager log --pretty="tformat:%s" -1 | grep -vqF "[skip-rtd]") || exit 183
      - git fetch --unshallow || true
    pre_install:
      - git update-index --assume-unchanged doc/conf.py ci/requirements/doc.txt

python:
  install:
    - requirements: ci/requirements/doc.txt

sphinx:
  configuration: doc/conf.py
  fail_on_warning: true

formats: []
