name: Linters

# Controls when the action will run. Triggers the workflow on push or pull request
# events but only for the master branch
on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  flake8:
    name: flake8
    runs-on: ubuntu-latest

    steps:
    - name: checkout the repository
      uses: actions/checkout@v2

    - name: setup python
      uses: actions/setup-python@v2
      with:
        python-version: 3.8

    - name: upgrade pip
      run: python -m pip install --upgrade pip

    - name: install dependencies
      run: python -m pip install -r ci/requirements/normal.txt

    - name: show versions
      run: python -m pip list

    - name: run flake8
      run: python -m flake8 .

  isort:
    name: isort
    runs-on: ubuntu-latest

    steps:
    - name: checkout the repository
      uses: actions/checkout@v2

    - name: setup python
      uses: actions/setup-python@v2
      with:
        python-version: 3.8

    - name: upgrade pip
      run: python -m pip install --upgrade pip

    - name: install dependencies
      run: python -m pip install -r ci/requirements/normal.txt

    - name: show versions
      run: python -m pip list

    - name: run isort
      run: python -m isort --diff --color .

  black:
    name: black
    runs-on: ubuntu-latest

    steps:
    - name: checkout the repository
      uses: actions/checkout@v2

    - name: setup python
      uses: actions/setup-python@v2
      with:
        python-version: 3.8

    - name: upgrade pip
      run: python -m pip install --upgrade pip

    - name: install dependencies
      run: python -m pip install -r ci/requirements/normal.txt

    - name: show versions
      run: python -m pip list

    - name: run black
      run: python -m black --diff --color .
